name: Unit Tests

on:
  push:
    branches:
      master

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-versions: [3.8, 3.9]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-versions }}
      - name: Install Geos for Mac
        if: runner.os == 'macos'
        run: brew install geos
      - name: Install Geos for Linux
        if: runner.os == 'ubuntu'
        run: apt-get install libgeos-dev
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install -r requirements.txt 
      - name: Run unit tests
        run: python -m pytest -vv
